#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod console;
pub mod console_2;
pub mod counter;
pub mod std_error;
pub mod std_json;
pub mod std_math;
pub mod std_storage;
pub mod vm;
